// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Novita - Tênis Esportivos de Qualidade",
  description: "Loja especializada em tênis esportivos das melhores marcas. Nike, Adidas, Puma e muito mais. Qualidade e estilo para seus pés.",
  keywords: "tênis, esportivos, Nike, Adidas, Puma, calçados, esportes, running, casual",
  authors: [{ name: "Novita" }],
  openGraph: {
    title: "Novita - Tênis Esportivos",
    description: "Os melhores tênis esportivos você encontra aqui!",
    type: "website",
    locale: "pt_BR",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}